version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test # Użyj swojego hasła 'test'
      POSTGRES_DB: mathsino-db # Użyj swojej nazwy bazy 'mathsino-db'
    ports:
      # --- STAŁE MAPOWANIE PORTÓW ---
      # Lewa strona to port Twojego hosta (KOMPUTERA)
      # Prawa strona to port WEWNĘTRZNY kontenera (5432)
      - "5432:5432" 
      # -------------------------------
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: