// <auto-generated />
using System;
using Mathsino.Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mathsino.Backend.Migrations
{
    [DbContext(typeof(MathsinoContext))]
    [Migration("20260114194057_AddGameStatePersistence")]
    partial class AddGameStatePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mathsino.Backend.Game.SingleGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceAfterGame")
                        .HasColumnType("integer");

                    b.Property<int>("BetAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameStateJson")
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SingleGameResult")
                        .HasColumnType("integer");

                    b.Property<int?>("SingleGameSplitResult")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SingleGames");
                });

            modelBuilder.Entity("Mathsino.Backend.Models.AdView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("integer");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RewardClaimedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AdViews");
                });

            modelBuilder.Entity("Mathsino.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastSpinTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LessonsCompleted")
                        .HasColumnType("integer");

                    b.Property<bool>("MusicEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MusicId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("SoundEffectsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "snake.png",
                            Balance = 5000,
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            Language = "en",
                            LastName = "Smith",
                            LastSpinTime = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            LessonsCompleted = 0,
                            MusicEnabled = true,
                            MusicId = 1,
                            Provider = "",
                            ProviderId = "",
                            SoundEffectsEnabled = true,
                            UserName = "alismi"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "mouse.png",
                            Balance = 3000,
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            Language = "en",
                            LastName = "Johnson",
                            LastSpinTime = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            LessonsCompleted = 0,
                            MusicEnabled = true,
                            MusicId = 1,
                            Provider = "",
                            ProviderId = "",
                            SoundEffectsEnabled = true,
                            UserName = "bobjoh"
                        });
                });

            modelBuilder.Entity("Mathsino.Backend.Models.UserFriend", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("UserFriends");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FriendId = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Mathsino.Backend.Game.SingleGame", b =>
                {
                    b.HasOne("Mathsino.Backend.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Mathsino.Backend.Models.AdView", b =>
                {
                    b.HasOne("Mathsino.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mathsino.Backend.Models.UserFriend", b =>
                {
                    b.HasOne("Mathsino.Backend.Models.User", "Friend")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mathsino.Backend.Models.User", "User")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mathsino.Backend.Models.User", b =>
                {
                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
