POST http://localhost:5126/user/3/balance/add?amount=50
Content-Type: application/json

###
GET http://localhost:5126/user/3/balance
Content-Type: application/json

@baseUrl = http://localhost:5126
@userId = 3
@authCookie = CfDJ8NMJWbf_erhLsiWN3cFDaYgcxLyX7yvSQ82Kv-8TAhW_5xRugaik8-NNSImfhYf6JfMgoDKUyVDFP1ZquQ3mrO7ZxL3zDBCqkRZ_ZIcxqIREjhCBjFqO0kNrszBde_n_S676aDgOGxHjNv8roY2gnc7eEE4Ev5ppIhGmja0zizozVoCTqkVIOMH2ihEWzh02TXCqUCwvZ5GDWN5WSdRp-lEgM1qqOBovVTm9X2TKSnpqw3JNL0cRuiJERszFbVX2YHhZjk8J_b8oBJEv0sWzV-pk3kQpzv5LX-GOrWhovv9gSUNxvcWv-hn0sG7N-aplO36j7nKfQadEQSHP-CK9X6hpO-k9By9ESvTBhG9batjdIc8vJedgp8yzCYvIQe6AraRp8QP7PBteObW4e4Cy2WGSa7EhcSbuu0VlzgZgqGvvK8kSdNwlzU-Lv9mP2hnhRKYcigXtCKqzZhmjLh_igMmor8wKHi_BdUmXDirOxxF_BhyuAZrXXl2_oDLbrJiJg_iLjhxeg4VuXdKE2uKXzNKK_AXEK-acA8_yEB5Tyw8SGUewNN3xvILRqH_jYL49Tg
###
POST {{baseUrl}}/user/{{userId}}/start-ad-view
Content-Type: application/json
//Cookie: MathsinoAuth={{authCookie}}

### 
POST {{baseUrl}}/user/{{userId}}/claim-ad-reward
Content-Type: application/json
Cookie: MathsinoAuth={{authCookie}}

{
  "token": "R4vFNWBkdPjXAKXXBbiZQw"
}

###
POST {{baseUrl}}/games/create-singleplayer?userId={{userId}}&betAmount=10
Content-Type: application/json
Cookie: MathsinoAuth={{authCookie}}
